container:
  image: termux/package-builder:latest
  cpu: 4
  memory: 8

task:
  name: Build

  # 2 hours is a maximal timeout available for free use.
  timeout_in: 120m

  environment:
    TERMUX_MAKE_PROCESSES: 4
    matrix:
      TERMUX_ARCH: aarch64
      TERMUX_ARCH: arm
      TERMUX_ARCH: i686
      TERMUX_ARCH: x86_64

  # Do not use built-in git client provided by Cirrus as may
  # cause problems when determining changed files.
  clone_script: |
    if [[ -z "$CIRRUS_PR" ]]; then
      git clone --recursive --branch="$CIRRUS_BRANCH" "https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git" "$CIRRUS_WORKING_DIR"
      git reset --hard "$CIRRUS_CHANGE_IN_REPO"
    else
      git clone --recursive "https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git" "$CIRRUS_WORKING_DIR"
      git fetch origin "pull/$CIRRUS_PR/head:pull/$CIRRUS_PR"
      git reset --hard "$CIRRUS_CHANGE_IN_REPO"
    fi

  build_script: |
    bash ./scripts/cirrus-ci_dispatcher.sh

  output_artifacts:
    path: "./termux-packages/debs/*.deb"

task:
  name: Publish

  only_if: $CIRRUS_BRANCH == 'master'

  timeout_in: 60m

  depends_on:
    - Build

  environment:
    BINTRAY_USERNAME: ENCRYPTED[!4f7278414220b7ea7d8e06e94edfebcf81e4bd766201201caa895a376571e50a324e6be3f3dc1aef0aec938a47f72dab!]
    BINTRAY_API_KEY: ENCRYPTED[!a60797f4f21f143f4a1ef45b9d4286fa56c3ddbc1d652d988bfd5cc864790befc614e25783379b3f76121f5141b3e29a!]
    BINTRAY_GPG_PASSPHRASE: ENCRYPTED[!1359cb14fc48ecba379001f06db6d1452a929b64d970345b84cc12b97a0f17a3be5adc34d56125a647470df7487dfec0!]

  upload_script: |
    bash ./scripts/cirrus-ci_dispatcher.sh --upload
